apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-demo
  name: busybox-demo
spec:
  containers:
  - image: busybox:latest
    name: busybox-demo
  initContainers:
  - name: waitfordns
    image: busybox
    command:
      - sh
      - -c
      - until nslookup mymysql; do echo "Trying to resolve..."; sleep 5; done
