apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-app
  template:
    metadata:
      labels:
        app: nginx-web-app
    spec:
      containers:
      - name: nginx-web-app
        image: caduunisal/cadu-web-app:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always